### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by joeblew99** [olebedev/go-duktape#30]
Any idea about speed penalty ?

**Comment by olebedev** [comment]
As I wrote at [reddit](https://www.reddit.com/r/golang/comments/2s2agu/duktape_bindings_for_go/) go-duktape slower than node around 2-5 times, maybe even slower. Mostly because C duktape don't have JIT and hidden classes optimisations. The main duktape's goal is not performance, it it portability and compact footprint. I needs to add some benchmarks into the repo to clarify this thing. I don't mind if somebody helps me with it.

**Comment by gedw99** [comment]
That's not bad. I was expecting 20 times slower.
Will give this a whirl

**Comment by olebedev** [comment]
Closed, see  https://github.com/olebedev/go-duktape#benchmarks

**Comment by joeblew99** [comment]
Thanks. Numbers look great. Awesome
